spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
<<<<<<< HEAD
    url: jdbc:oracle:thin:@db20220704095701_high?TNS_ADMIN=D:/SimJ/Wallet_DB20220704095701
=======
    url: jdbc:oracle:thin:@db20220622131615_high?TNS_ADMIN=C:/Joo/Wallet_DB20220622131615
>>>>>>> 7fb256faffbc9bd0b15646b2a2493ac6fa2694e6
    username: admin
    password:

