spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
<<<<<<< HEAD
    url: jdbc:oracle:thin:@db20220721173355_high?TNS_ADMIN=
    username: admin
    password: 
=======
    url : jdbc:oracle:thin:@db20220704095701_high?TNS_ADMIN=C:/Wallet_DB20220704095701
    username: admin
    password: Gksehdgh121!


>>>>>>> a2354f7132faa8d3f7eb9baa879697da7fe5a5ea
