spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db20220622131615_high?TNS_ADMIN=C:/Joo/Wallet_DB20220622131615
    username: admin
    password: Jooyeoun1234