spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
<<<<<<< HEAD
    url : jdbc:oracle:thin:@db20220704095701_high?TNS_ADMIN=C:/java_1900_hdh/classcontent/Wallet_DB20220704095701
=======
    url : jdbc:oracle:thin:@db20220622131615_high?TNS_ADMIN=C:/Joo/Wallet_DB20220622131615
>>>>>>> bc9bbdac6f7bdec022ebe38d74825f43d6c6afe8
    username: admin
    password: 