spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@db20220721173355_high?TNS_ADMIN=C:/Users/PC/Desktop/triple/Wallet_DB20220721173355
    username: admin
    password: Ka66414312514!
